//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The3BlackBro.WebQueue.Service.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The3BlackBro.WebQueue.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No amount was found for this company..
        /// </summary>
        public static string mAmountNotFound {
            get {
                return ResourceManager.GetString("mAmountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete owner user..
        /// </summary>
        public static string mCantDeleteOwnerUser {
            get {
                return ResourceManager.GetString("mCantDeleteOwnerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regist could not be deleted, because there&apos;s relation between other tables. The regist was marked as &quot;not Activated&quot;..
        /// </summary>
        public static string mCantDeleteThereIsRelation {
            get {
                return ResourceManager.GetString("mCantDeleteThereIsRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This company is not associated to this user..
        /// </summary>
        public static string mCompanyNotAssociatedToThisUser {
            get {
                return ResourceManager.GetString("mCompanyNotAssociatedToThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company was not found..
        /// </summary>
        public static string mCompanyNotFound {
            get {
                return ResourceManager.GetString("mCompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is already in queue.
        /// </summary>
        public static string mCustomerAlreadyInQueue {
            get {
                return ResourceManager.GetString("mCustomerAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was deleted..
        /// </summary>
        public static string mCustomerDeleted {
            get {
                return ResourceManager.GetString("mCustomerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is not in service to be finished..
        /// </summary>
        public static string mCustomerIsNotInService {
            get {
                return ResourceManager.GetString("mCustomerIsNotInService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string mCustomerNotFound {
            get {
                return ResourceManager.GetString("mCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use..
        /// </summary>
        public static string mEmailAlreadyInUse {
            get {
                return ResourceManager.GetString("mEmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro while processing..
        /// </summary>
        public static string mErrorInProcess {
            get {
                return ResourceManager.GetString("mErrorInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find company with id {0}.
        /// </summary>
        public static string mNoCompanyWasFoundWithId {
            get {
                return ResourceManager.GetString("mNoCompanyWasFoundWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more customers..
        /// </summary>
        public static string mNoMoreCustomers {
            get {
                return ResourceManager.GetString("mNoMoreCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No owner was found..
        /// </summary>
        public static string mNoOwnerUserWasFound {
            get {
                return ResourceManager.GetString("mNoOwnerUserWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t has permission to start a queue..
        /// </summary>
        public static string mNoPermissionStartQueue {
            get {
                return ResourceManager.GetString("mNoPermissionStartQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queu was found with id {0}.
        /// </summary>
        public static string mNoQueueWasFound {
            get {
                return ResourceManager.GetString("mNoQueueWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service was found.
        /// </summary>
        public static string mNoServiceWasFound {
            get {
                return ResourceManager.GetString("mNoServiceWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service was found for this company..
        /// </summary>
        public static string mNoServiceWasFoundForThisCompany {
            get {
                return ResourceManager.GetString("mNoServiceWasFoundForThisCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service was found for this customer..
        /// </summary>
        public static string mNoServiceWasFoundForThisCustomer {
            get {
                return ResourceManager.GetString("mNoServiceWasFoundForThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find user with id {0}.
        /// </summary>
        public static string mNoUserWasFoundWithId {
            get {
                return ResourceManager.GetString("mNoUserWasFoundWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string mOk {
            get {
                return ResourceManager.GetString("mOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue already  started for {0}..
        /// </summary>
        public static string mQueueAlreadyStarted {
            get {
                return ResourceManager.GetString("mQueueAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company is not associated to user..
        /// </summary>
        public static string mQueueCompanyNotAssociatedToUser {
            get {
                return ResourceManager.GetString("mQueueCompanyNotAssociatedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue for company {0} ended sucessfully.
        /// </summary>
        public static string mQueueEnded {
            get {
                return ResourceManager.GetString("mQueueEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue is not available..
        /// </summary>
        public static string mQueueNotAvailable {
            get {
                return ResourceManager.GetString("mQueueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue started suceed for {0}..
        /// </summary>
        public static string mQueueStartedSuceed {
            get {
                return ResourceManager.GetString("mQueueStartedSuceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue started sucessfully for company id {0}.
        /// </summary>
        public static string mQueueSucessStarted {
            get {
                return ResourceManager.GetString("mQueueSucessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not allowed to create a queue.
        /// </summary>
        public static string mQueueUserNotAuthorized {
            get {
                return ResourceManager.GetString("mQueueUserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned all customers in queue with id {0}.
        /// </summary>
        public static string mReturnedAllCustomersInQueue {
            get {
                return ResourceManager.GetString("mReturnedAllCustomersInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Created..
        /// </summary>
        public static string mSucceedCreated {
            get {
                return ResourceManager.GetString("mSucceedCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted..
        /// </summary>
        public static string mSuceedDeleted {
            get {
                return ResourceManager.GetString("mSuceedDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessfullyUpdated..
        /// </summary>
        public static string mSuceedUpdated {
            get {
                return ResourceManager.GetString("mSuceedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no open amount today for company id {0}.
        /// </summary>
        public static string mThereNoAmountForToday {
            get {
                return ResourceManager.GetString("mThereNoAmountForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount was updated..
        /// </summary>
        public static string mUpdateAmount {
            get {
                return ResourceManager.GetString("mUpdateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User inserted in queue in {0}..
        /// </summary>
        public static string mUserInsertedInQueue {
            get {
                return ResourceManager.GetString("mUserInsertedInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user was found..
        /// </summary>
        public static string mUserNotFound {
            get {
                return ResourceManager.GetString("mUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s services updated.
        /// </summary>
        public static string mUserServicesUpdated {
            get {
                return ResourceManager.GetString("mUserServicesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s services are already done.
        /// </summary>
        public static string mUsersServicesAlreadyDone {
            get {
                return ResourceManager.GetString("mUsersServicesAlreadyDone", resourceCulture);
            }
        }
    }
}
